name: esp32_cam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  app_settings: ^5.2.0
  network_info_plus: ^6.1.3
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.2
  wifi_iot: ^0.3.19
  flutter_blue_plus: ^1.35.3
  http: ^1.3.0
  multicast_dns: ^0.3.2+8
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
